const movieArray = [
    "The Godfather",
    "The Shawshank Redemption",
    "The Dark Knight",
    "Pulp Fiction",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "The Hobbit: An Unexpected Journey",
    "The Hobbit: The Desolation of Smaug",
    "The Hobbit: The Battle of the Five Armies",
    "Forrest Gump",
    "The Matrix",
    "The Silence of the Lambs",
    "The Lion King",
    "The Shining",
    "The Terminator",
    "The Exorcist",
    "The Sixth Sense",
    "The Green Mile",
    "The Departed",
    "The Truman Show",
    "The Breakfast Club",
    "The Big Lebowski",
    "The Grand Budapest Hotel",
    "The Social Network",
    "The King's Speech",
    "The Artist",
    "The Shape of Water",
    "The Revenant",
    "The Hurt Locker",
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Chamber of Secrets",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Half-Blood Prince",
    "Harry Potter and the Deathly Hallows: Part 1",
    "Harry Potter and the Deathly Hallows: Part 2",
    "Twilight",
    "New Moon",
    "Eclipse",
    "Breaking Dawn: Part 1",
    "Breaking Dawn: Part 2",
    "The Hunger Games",
    "Catching Fire",
    "Mockingjay: Part 1",
    "Mockingjay: Part 2",
    "The Maze Runner",
    "The Scorch Trials",
    "The Death Cure",
    "The Giver",
    "The Divergent",
    "Insurgent",
    "Allegiant",
    "The Fault in Our Stars",
    "The Spectacular Now",
    "The Perks of Being a Wallflower",
    "Battle Royale",
    "Batman Begins",   
    "The Dark Knight Rises",
    "The Dark Knight",
    "Inception",
    "Interstellar",
    "Dunkirk",
    "Memento",
    "The Prestige",
    "How to Train Your Dragon",
    "How to Train Your Dragon 2",
    "How to Train Your Dragon: The Hidden World",
    "Shrek",
    "Shrek 2",
    "Shrek the Third",
    "Shrek Forever After",
    "Kung Fu Panda",
    "Kung Fu Panda 2",
    "Kung Fu Panda 3",
    "Madagascar",
    "Madagascar: Escape 2 Africa",
    "Madagascar 3: Europe's Most Wanted",
    "Madagascar 4",
    "Monsters, Inc.",
    "Monsters University",
    "Finding Nemo",
    "Finding Dory",
    "Toy Story",
    "Toy Story 2",
    "Toy Story 3",
    "Toy Story 4",
    "Cars",
    "Cars 2",
    "Cars 3",
    "Ratatouille",
    "The Incredibles",
    "The Incredibles 2",
    "Up",
    "Inside Out",
    "Coco",
    "Moana",
    "Frozen",
    "Frozen II",
    "Tangled",
    "Brave",
    "Big Hero 6",
    "Zootopia",
    "The Jungle Book",
    "The Little Mermaid",
    "Beauty and the Beast",
    "Aladdin",
    "Mulan",
    "Pocahontas",
    "The Princess and the Frog",
    "Robin Hood",
    "Rocky",
    "Rocky II",
    "Rocky III",
    "Rocky IV",
    "Rocky V",
    "Rocky Balboa",
    "Creed",
    "Creed II",
    "The Karate Kid",
    "The Karate Kid II",
    "The Karate Kid III",
    "The Next Karate Kid",
    "Star Wars: Episode I - The Phantom Menace",
    "Star Wars: Episode II - Attack of the Clones",
    "Star Wars: Episode III - Revenge of the Sith",
    "Star Wars: Episode IV - A New Hope",
    "Star Wars: Episode V - The Empire Strikes Back",
    "Star Wars: Episode VI - Return of the Jedi",
    "Star Wars: Episode VII - The Force Awakens",
    "Star Wars: Episode VIII - The Last Jedi",
    "Star Wars: Episode IX - The Rise of Skywalker",
    "Rogue One: A Star Wars Story",
    "Solo: A Star Wars Story",
    "Gray's Anatomy",
    "The Office",
    "Friends",
    "The Big Bang Theory",
    "Breaking Bad",
    "The Walking Dead",
    "Stranger Things",
    "Game of Thrones",
    "The Mandalorian",
    "The Witcher",
    "The Crown",
    "The Queen's Gambit",
    "The Umbrella Academy",
    "The Haunting of Hill House",
    "The Haunting of Bly Manor",
    "Barbie",
    "Oppenheimer",
    "The Matrix",
    "The Matrix Reloaded",
    "The Matrix Revolutions",
    "The Matrix Resurrections",
    "Children of the Corn",
    "The Shining",
    "Doctor Sleep",
    "The Stand",
    "The Dark Tower",
    "The Mist",
    "The Green Mile",
    "Carrie",
    "The Dead Zone",
    "The Running",
    "The Long Walk",
    "Miss Peregrine's Home for Peculiar Children",
    "Percy Jackson & the Olympians: The Lightning Thief",
    "Percy Jackson: Sea of Monsters",
    "Percy Jackson and the Olympians",
];

function getRandomMovie() {
    let randomMovie = Math.floor(Math.random() * movieArray.length);
    console.log(randomMovie);
    return movieArray[randomMovie];
}

export default {getRandomMovie};